services:

  esphome-audio-file-converter:
    container_name: esphome-audio-file-converter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DEBUG=true
    stdin_open: true
    tty: true
